#!/usr/bin/env bash
# Regenerate src/engine/EmojiTable.cpp from the Unicode emoji-test.txt data file.
# Skin-tone variants and the Component group are dropped; what is left is the base emoji set the
# picker offers. Coverage is filtered again at runtime against the installed emoji font.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/src/engine/EmojiTable.cpp"
URL="${EMOJI_TEST_URL:-https://unicode.org/Public/emoji/latest/emoji-test.txt}"

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to generate the emoji table." >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
curl -fsSL "$URL" -o "$tmp"

python3 - "$tmp" "$DEST" <<'PY'
import re, sys

src, dest = sys.argv[1], sys.argv[2]

SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}
version = "unknown"
group = subgroup = ""
groups, entries = [], []

with open(src, encoding="utf-8") as handle:
    for line in handle:
        line = line.rstrip("\n")
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
            continue
        if line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
            continue
        if line.startswith("# subgroup:"):
            subgroup = line.split(":", 1)[1].strip()
            continue
        if not line or line.startswith("#"):
            continue

        codes, _, rest = line.partition(";")
        status, _, comment = rest.partition("#")
        if status.strip() != "fully-qualified" or group == "Component":
            continue

        points = [int(code, 16) for code in codes.split()]
        if any(point in SKIN_TONES for point in points):
            continue

        # "# 😀 E1.0 grinning face" — the name is everything after the version tag.
        name = re.sub(r"^\s*\S+\s+E\d+(\.\d+)?\s*", "", comment)
        if not name:
            continue

        if group not in groups:
            groups.append(group)
        entries.append((points, name, subgroup.replace("-", " "), groups.index(group)))

def literal(points):
    return "".join("\\U%08X" % point for point in points)

def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')

with open(dest, "w", encoding="utf-8") as out:
    out.write("// Generated by scripts/sync-emoji-table.sh from Unicode emoji-test.txt "
              "(Emoji %s).\n// Do not edit by hand.\n\n" % version)
    out.write('#include "EmojiTable.h"\n\nnamespace drift::emoji {\n\n')
    out.write("const char *const kGroups[] = {\n")
    for name in groups:
        out.write('    "%s",\n' % escape(name))
    out.write("};\nconst int kGroupCount = %d;\n\n" % len(groups))
    out.write("const TableEntry kTable[] = {\n")
    for points, name, keywords, index in entries:
        out.write('    {"%s", "%s", "%s", %d},\n'
                  % (literal(points), escape(name), escape(keywords), index))
    out.write("};\nconst int kTableSize = %d;\n\n} // namespace drift::emoji\n" % len(entries))

print("Wrote %d emoji in %d groups (Emoji %s) to %s" % (len(entries), len(groups), version, dest))
PY
